from mConsole import oConsole;

from fPrintLogo import fPrintLogo;
from mColors import *;

def fPrintUsageInformation():
  oConsole.fLock();
  try:
    fPrintLogo();
    axBoolean = ["[=", INFO, "true", NORMAL, "|", INFO, "false", NORMAL, "]"];
    
    oConsole.fOutput(HILITE,"Usage:");
    oConsole.fOutput();
    oConsole.fOutput(INFO,"  rs.py [options] [<path> [<path> [...]]] [-- <command>]");
    oConsole.fOutput();
    oConsole.fOutput(HILITE, "Options:");
    oConsole.fOutput("  ", INFO, "-h", NORMAL, ", ", INFO, "--help");
    oConsole.fOutput("    This cruft.");
    oConsole.fOutput("  ", INFO, "--version");
    oConsole.fOutput("    Show version information.");
    oConsole.fOutput("  ", INFO, "--version-check");
    oConsole.fOutput("    Check for updates and show version information.");
    oConsole.fOutput("  ", INFO, "--license");
    oConsole.fOutput("    Show license information.");
    oConsole.fOutput("  ", INFO, "--license-update");
    oConsole.fOutput("    Download license updates and show license information.");
    oConsole.fOutput("  ", INFO, "--arguments", NORMAL, "=<", INFO, "file path", NORMAL, ">");
    oConsole.fOutput("    Load additional arguments from the provided value and insert them in place");
    oConsole.fOutput("    of this argument.");
    
    oConsole.fOutput("  ", INFO, "-q", NORMAL, ", ", INFO, "--quiet", axBoolean);
    oConsole.fOutput("    Output only essential information.");
    oConsole.fOutput("  ", INFO, "-v", NORMAL, ", ", INFO, "--verbose", axBoolean);
    oConsole.fOutput("    Verbose output.");
    oConsole.fOutput("  ", INFO, "-p", NORMAL, ", ", INFO, "--pause", axBoolean);
    oConsole.fOutput("    Wait for user to press ENTER before terminating.");
    oConsole.fOutput("  ", INFO, "-u", NORMAL, ", ", INFO, "--unicode", axBoolean);
    oConsole.fOutput("    Remove all '\0' chars from the file before scanning to improvise scanning");
    oConsole.fOutput("    utf-16 encoded ASCII characters.");
    oConsole.fOutput("  ", INFO, "-e", NORMAL, ", ", INFO, "--uedit", axBoolean);
    oConsole.fOutput("    Start UltraEdit 64-bit for each matched file and scroll to the first matched line (if any).");
    oConsole.fOutput("  ", INFO, "-l", NORMAL, ", ", INFO, "--lines <lines>");
    oConsole.fOutput("    Show the provided number of lines of the file's content around each match.");
    oConsole.fOutput("    ", INFO, "<lines>", NORMAL, " can take two formats: ", INFO, "[-/+]N", NORMAL, " and ", INFO, "-N+N", NORMAL, ".");
    oConsole.fOutput("    Where N is a integer number, positive/negative numbers determine the number");
    oConsole.fOutput("    of lines to show after/before the match respectively.");
    oConsole.fOutput("  ", INFO, "<path>", NORMAL, " [", INFO, "<path>", NORMAL, " [", INFO, "...", NORMAL, "]]");
    oConsole.fOutput("    Apply matching only to the provided files/folders. If not path is");
    oConsole.fOutput("    provided, the current working directory is used.");
    oConsole.fOutput("  ", INFO, "-r", NORMAL, ", ", INFO, "--recursive");
    oConsole.fOutput("    Apply matching to all files in all subfolders of the selected folders.");
    oConsole.fOutput("  ", INFO, "<regular expression> [<regular expression> [...]]");
    oConsole.fOutput("    Match the content or full path and name of files against the given regular");
    oConsole.fOutput("    expression(s). You must provide at least one regular expression.");
    oConsole.fOutput(HILITE, "Regular expression syntax:");
    oConsole.fOutput("  [", INFO, "c", NORMAL, "|", INFO, "p", NORMAL, "]",
                       "[", INFO, "!", NORMAL, "]",
                       "/", INFO, "pattern", NORMAL, "/",
                       "[", INFO, "flags", NORMAL, "]");
    oConsole.fOutput();
    oConsole.fOutput("  [", INFO, "c", NORMAL, "|", INFO, "p", NORMAL, "]");
    oConsole.fOutput("   ", INFO, "c", NORMAL, " indicates the regular expression should be matched against the file's content");
    oConsole.fOutput("   (default). ", INFO, "p", NORMAL, " indicates the regular expression should be matched against the");
    oConsole.fOutput("    file's full path and name.");
    oConsole.fOutput("  [", INFO, "!", NORMAL, "]");
    oConsole.fOutput("    If ", INFO, "!", NORMAL, "is present, the match is inverted: files that match this regular expression");
    oConsole.fOutput("    are ", UNDERLINE, "excluded", NORMAL, " from the result instead of included. File that ", UNDERLINE, "do not", NORMAL, " match");
    oConsole.fOutput("    this regular expression are included.");
    oConsole.fOutput("  ", INFO, "pattern");
    oConsole.fOutput("    A regular expression pattern following Python syntax.");
    oConsole.fOutput("  ", INFO, "flags");
    oConsole.fOutput("    Any one of the single-letter regular expression flags available in Python.");
    oConsole.fOutput();
    oConsole.fOutput("  For details on the syntax of Python regular expression patterns and flags");
    oConsole.fOutput("  please visit: ", INFO, "https://docs.python.org/3/library/re.html", NORMAL, ".");
    oConsole.fOutput("  ", INFO, "--", NORMAL, " <", INFO, "command", NORMAL, "> [", INFO, "arguments", NORMAL, "]");
    oConsole.fOutput("    Execute the specified command for all files that matched the given");
    oConsole.fOutput("    regular expressions. The command nad arguments can contain the following");
    oConsole.fOutput("    keys that will be replaced by the appropriate values:");
    oConsole.fOutput("      ", INFO, "{d}", NORMAL, " - the drive on which the file was found.");
    oConsole.fOutput("      ", INFO, "{p}", NORMAL, " - the folder path in which the file was found.");
    oConsole.fOutput("      ", INFO, "{n}", NORMAL, " - the name of the file (excluding the extension).");
    oConsole.fOutput("      ", INFO, "{x}", NORMAL, " - the extension of the file (including the dot).");
    oConsole.fOutput("      ", INFO, "{f}", NORMAL, " - the full path of the file (== ", INFO, "{dpnx}", NORMAL, ").");
    oConsole.fOutput("    Note: The above arguments can be combined: ", INFO, "{dp}", NORMAL, " will be replaced with the");
    oConsole.fOutput("    file's drive and path, and ", INFO, "{nx}", NORMAL, " will be replaced by the file's name and");
    oConsole.fOutput("    extension. The values for these keys will be surrounded by quotes unless");
    oConsole.fOutput("    preceed them with ", INFO, "~", NORMAL, " (e.g. ", INFO, "\"{~n}{~x}\"", NORMAL, " == ", INFO, "{nx}", NORMAL, ").");
    oConsole.fOutput("      ", INFO, "{l}", NORMAL, " - the line number on which the first match was found.");
    oConsole.fOutput("    Note: Repeating {l} gives you the next line number on which a match was");
    oConsole.fOutput("    found, or -1 if there are no more matches: {l},{l},{l} will be replaced with");
    oConsole.fOutput("    the line numbers of the first three matches, separated by commas.");
    oConsole.fOutput("      ", INFO, "{1}", NORMAL, ", ", INFO, "{2}", NORMAL, ", ", INFO, "{3}", NORMAL, "... - the ", UNDERLINE, "first path", NORMAL, " match's sub-matches.");
    oConsole.fOutput("    Note: You can use {1} - {9} to insert parts of the first match against the");
    oConsole.fOutput("    file path. This may be useful to mass-rename files.");
    oConsole.fOutput();
    oConsole.fOutput(HILITE, "Examples:");
    oConsole.fOutput("  ", INFO, "rs /C+/ -p /P+/ -r");
    oConsole.fOutput("    Match all files in the current directory and all its sub-folders which path");
    oConsole.fOutput("    and name contains a sequence of 1 or more 'P'-s. Match the  content of ");
    oConsole.fOutput("    these files for a sequence of 1 or more 'C'-s. Output the path and name of");
    oConsole.fOutput("    the files that matched and the line number(s) on which the 'C'-s were found.");
    oConsole.fOutput();
    oConsole.fOutput("  ", INFO, "rs -p /P+/i C:\\ -r");
    oConsole.fOutput("    Match all files in the root of the C: drive and all its sub-folders which");
    oConsole.fOutput("    path and name contains a sequence of 1 or more 'p'-s (either upper- or");
    oConsole.fOutput("    lowercase). Output the path and name of the files that matched.");
    oConsole.fOutput();
    oConsole.fOutput("  ", INFO, "rs /class\\s+\\w+/m -p /\\.c(pp|xx)$/i -- notepad {f}");
    oConsole.fOutput("    Match all files in the current folder that have a .cpp or .cxx extension.");
    oConsole.fOutput("    Match the content of these files against a C++ class definitions. Output");
    oConsole.fOutput("    the path, name and line numbers of the files and open each one in Notepad.");
    oConsole.fOutput();
    oConsole.fOutput("  ", INFO, "rs /struct\s+some_struct\s*{/m -r -p /\\.[ch](pp|xx)?$/i -l -1+16");
    oConsole.fOutput("    Match all files in the current folder that have a C/C++ extension.");
    oConsole.fOutput("    Match the content of these files against the struct some_struct");
    oConsole.fOutput("    definitions. Output the path and name of the matched file(s) and the line");
    oConsole.fOutput("    before and up to 16 lines after each match.");
    oConsole.fOutput();
    oConsole.fOutput(HILITE, "Exit codes:");
    oConsole.fOutput("  ", INFO, "0", NORMAL," = rs did not match any files.");
    oConsole.fOutput("  ", INFO, "1", NORMAL," = rs matched one or more files.");
    oConsole.fOutput("  ", ERROR_INFO, "2", NORMAL, " = rs was unable to parse the command-line arguments provided.");
    oConsole.fOutput("  ", ERROR_INFO, "3", NORMAL, " = rs ran into an internal error: please report the details!");
  finally:             
    oConsole.fUnlock();